acmeair-booking-db:
  container_name: acmeair-booking-db
  image: mongo
  net: ${NETWORK}

acmeair-customer-db:
  container_name: acmeair-customer-db
  image: mongo
  net: ${NETWORK}

acmeair-flight-db:
  container_name: acmeair-flight-db
  image: mongo
  net: ${NETWORK}

acmeair-nginx1:
  container_name: acmeair-nginx1
  net: ${NETWORK}
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - /www/public
  volumes_from:
    - acmeair-mainservice-java
    - acmeair-authservice-java
    - acmeair-bookingservice-java
    - acmeair-customerservice-java
    - acmeair-flightservice-java

acmeair-mainservice-java:
  container_name: acmeair-mainservice-java
  net: ${NETWORK}
  build: ../acmeairmainservice/
  environment:
    - LICENSE=accept

acmeair-authservice-java:
  container_name: acmeair-authservice-java
  net: ${NETWORK}
  build: ../acmeairauthservice/
  environment:
    - LICENSE=accept

acmeair-bookingservice-java:
  container_name: acmeair-bookingservice-java
  net: ${NETWORK}
  build: ../acmeairbookingservice/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-booking-db
  volumes_from:
    - acmeair-booking-db

acmeair-customerservice-java:
  container_name: acmeair-customerservice-java
  net: ${NETWORK}
  build: ../acmeaircustomerservice/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-customer-db
  volumes_from:
    - acmeair-customer-db

acmeair-flightservice-java:
  container_name: acmeair-flightservice-java
  net: ${NETWORK}
  build: ../acmeairflightservice/
  environment:
    - LICENSE=accept
    - MONGO_HOST=acmeair-flight-db
  volumes_from:
    - acmeair-flight-db
